/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyJNIClass */

#ifndef _Included_MyJNIClass
#define _Included_MyJNIClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyJNIClass
 * Method:    X
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_MyJNIClass_X
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
